# fly.toml file generated for rocketship-v3 on 2023-04-25T20:39:38+08:00

app = "rocketship-v3"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DATABASE_URL="postgres://postgres:xM2RbROgDZJko0z@[fdaa:1:722d:0:1::5]:5432/rocketship"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[deploy]
  release_command = "npx sequelize-cli  db:seed --seed 20230325083101-seed-user-skills.js --url 'postgres://postgres:xM2RbROgDZJko0z@[fdaa:1:722d:0:1::5]:5432/rocketship'"